name: CI/CD Pipeline on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Specifies Windows environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'  # Update to Node.js 16.13 or later

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run vulnerability scan
        run: npm audit
